### ISSUE TITLE
Package name available

### ISSUE THREAD

**Issue by 1egoman** [medikoo/clock#1]
@medikoo As this package is deprecated and no longer maintained, I'm wondering whether this package name is available. I'm working on an interesting utility that can be used to track the time a user spends working on a codebase and `clock` would be a perfect name for it.

**Comment by medikoo** [comment]
@1egoman I'd love to pass it, but I need to be sure that new owner can publish only v0.2+ versions. 
As far as I know npm doesn't provide such granularity at this point, until then I need to keep it with me.

**Comment by 1egoman** [comment]
@medikoo As of a year ago, npm removed the ability to `npm publish -f` and overwrite a previous version, even by another author. See http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f for more info.

**Comment by medikoo** [comment]
@1egoman yes I know about, but still publish of `0.1.7` is possible, and publishing there something not expected, will break some versions of packages I maintain.

**Comment by medikoo** [comment]
@1egoman if you're still into it. I can pass package name to you. Let me know
